export const NUMBER_OF_DEFAULT_COLUMNS = 3;
export const DEFAULT_UNSELECTED_ANSWER = "0";
export const DEFAULT_SELECTED_ANSWER = "1";
export const MAX_LENGTH_MAJOR = 35;
export const MATH_SUBJECT_NAME = "Toán";
export const PHYSICS_SUBJECT_NAME = "Vật lý";
export const CHEMISTRY_SUBJECT_NAME = "Hóa học";
export const ENGLISH_SUBJECT_NAME = "Tiếng Anh";
export const BIOLOGY_SUBJECT_NAME = "Sinh học";
export const GEOGRAPHY_SUBJECT_NAME = "Địa lý";
export const HISTORY_SUBJECT_NAME = "Lịch sử";
export const HUMANITY_SUBJECT_NAME = "Giáo dục công dân";
export const LITERARY_SUBJECT_NAME = "Ngữ văn";
export const DIALOG_CONFIRM_OPTION = 1;
export const DIALOG_CANCEL_OPTION = 0;

export const ROLE_ADMIN = 3;
export const ROLE_STUDENT = 2;
export const ROLE_STAFF = 1;